import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import {
  Header,
  Content,
  AboutMe,
  Skills,
  Repositories,
  BlindsEffect,
} from "@/components/export";
import { gsap } from "gsap";
import debounce from "@/controllers/debounce";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
import "swiper/css/navigation";
// import required modules
import { EffectCoverflow, Pagination, Parallax, Navigation } from "swiper";

interface Scroll {
  focus?: boolean;
  up?: boolean;
  down?: boolean;
  page: number;
  current?: number;
}

export default function Home(): JSX.Element {
  const itemsRef = useRef<HTMLDivElement>(null);
  const [activeTab, setActiveTab] = useState("Welcome");
  const [page, setPage] = useState(0);
  const swiperRef = useRef(null);

  const [scroll, setScroll] = useState<Scroll>({
    focus: false,
    up: false,
    down: false,
    page: 0,
    current: 0,
  });
  const listTab = [
    "Welcome",
    "Perfil",
    "Habilidades",
    "Escolaridade",
    "Projetos",
  ];
  const gsapParms = {
    end: {
      opacity: 1,
      x: 0,
      duration: 1.5,
      delay: 0.2,
      ease: "power3.out",
    },
    start: {
      opacity: 0,
      x: -500,
      duration: 1,
      delay: 0,
      ease: "power3.out",
    },
  };

  useEffect(() => {
    const swipeNext = document.querySelector(".swiper-button-next");
    const swipePrev = document.querySelector(".swiper-button-prev");
    swipeNext?.addEventListener("click", () => {
      setPage(swiperRef?.current?.swiper.activeIndex);
    });

    swipePrev?.addEventListener("click", () => {
      setPage(swiperRef?.current?.swiper.activeIndex);
    });

    () => {};
  }, [page]);

  return (
    <>
      <Head>
        <title>Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <script
          src="https://platform.linkedin.com/badges/js/profile.js"
          async
          defer
          type="text/javascript"
        ></script> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Header
        activeTab={activeTab}
        listTab={listTab}
        onClick={handleActiveTab}
      /> */}
      <main className="overflow-hidden">
        <Swiper
          style={{
            "--swiper-navigation-color": "#fff",
            "--swiper-pagination-color": "#fff",
          }}
          speed={600}
          parallax={true}
          pagination={{
            clickable: true,
          }}
          navigation={true}
          modules={[Parallax, Pagination, Navigation]}
          className="mySwiper h-full overflow-hidden"
          ref={swiperRef}
        >
          <div
            slot="container-start"
            className="parallax-bg"
            data-swiper-parallax="-23%"
          ></div>
          <SwiperSlide style={{ paddingTop: "0" }} className="p-1 sm:p-12">
            <Content
              className={`bg-welcome `}
              title={`BEM VINDO AO MEU PORTIFOLIO`}
            >
              <BlindsEffect />
            </Content>
          </SwiperSlide>
          <SwiperSlide>
            <Content className={`bg-content-1 aboutMe`} title={`Sobre mim`}>
              <AboutMe page={page} />
            </Content>
          </SwiperSlide>
          <SwiperSlide>
            <Content
              className={`bg-content-2 skills jello-horizontal gap-16`}
              title={`Habilidades`}
            >
              <Skills />
            </Content>
          </SwiperSlide>
          <SwiperSlide>
            <Content className={`bg-content-4 repositories`} title={`Projetos`}>
              <Repositories />
            </Content>
          </SwiperSlide>
        </Swiper>
        {/* 
        <div className="relative flex flex-col items-center" ref={itemsRef}>
          <Content
            className={`bg-welcome`}
            title={`BEM VINDO AO MEU PORTIFOLIO`}
          >
            <BlindsEffect />
          </Content>

          <Content className={`bg-content-1 aboutMe`} title={`Sobre mim`}>
            <AboutMe />
          </Content>

          <Content
            className={`bg-content-2 skills jello-horizontal gap-16`}
            title={`Habilidades`}
          >
            <Skills />
          </Content>
          {/* <Content className={`bg-content-3`} title={`Escolaridade`}>
            <Schooling />
          </Content> 
          <Content className={`bg-content-4 h-screen`} title={`Projetos`}>
            <Repositories />
          </Content>
        </div> */}
      </main>
    </>
  );
}
