import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import {
  AboutMe,
  Skills,
  Repositories,
  BlindsEffect,
  ContactMe,
  Hexagonal,
} from "@/components/export";

// Import Swiper React components
import { Swiper, SwiperRef, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
import "swiper/css/navigation";

// import required modules
import { Pagination, Navigation, EffectCreative } from "swiper";
import React from "react";

export default function Home(): JSX.Element {
  const [page, setPage] = useState<number>(0);
  const swiperRef = useRef<SwiperRef>(null);
  const classDefault =
    "relative !flex flex-col items-center text-white spacing_content bg-animation";

  return (
    <>
      <Head>
        <title>Portfólio de Flávio Leonardo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Swiper
        navigation={true}
        pagination={{ clickable: true }}
        grabCursor={true}
        // direction={"vertical"}
        effect={"creative"}
        speed={1400}
        creativeEffect={{
          prev: {
            // shadow: true,
            translate: [0, 0, -200],
          },
          next: {
            translate: ["100%", 0, 0],
          },
        }}
        modules={[EffectCreative, Navigation, Pagination]}
        className="mySwiper bg-animation h-full "
        ref={swiperRef}
        onActiveIndexChange={(e) => {
          setPage(e?.activeIndex);
        }}
      >
        <SwiperSlide className={`${classDefault} welcome sm:p-12`}>
          <h2
            className={`absolute px-10 text-center text-3xl font-semibold sm:text-5xl`}
          >
            Olá, me chamo Flávio
            <br />
            BEM VINDO AO MEU PORTIFOLIO
          </h2>

          <BlindsEffect />
          {/* <div className="absolute bottom-52">
            <Hexagonal />
          </div> */}
        </SwiperSlide>

        <SwiperSlide className={`${classDefault} aboutMe`}>
          <h2 className="mb-12 text-5xl font-semibold">Sobre mim</h2>
          <AboutMe page={page} />
        </SwiperSlide>

        <SwiperSlide className={`${classDefault} skills`}>
          <h2 className="mb-12 text-5xl font-semibold">Habilidades</h2>
          <Skills />
        </SwiperSlide>

        <SwiperSlide className={`${classDefault} repositories`}>
          <h2 className="mb-12 text-5xl font-semibold">Projetos</h2>
          <Repositories page={page} />
        </SwiperSlide>

        <SwiperSlide className={`${classDefault} contactMe`}>
          <h2 className="mb-12 text-5xl font-semibold">Contate me</h2>
          <ContactMe />
        </SwiperSlide>
      </Swiper>
    </>
  );
}
